export const POPULAR_INDUSTRIES = [
  // Finance & Banking
  "Finance",
  "Banking",
  "Investment Banking",
  "Private Equity",
  "Venture Capital",
  "Asset Management",
  "Insurance",
  "FinTech",
  "Cryptocurrency",
  "Wealth Management",
  "Credit",
  "Payment Processing",
  "Trading",
  "Risk Management",
  "Compliance",

  // Technology
  "Technology",
  "Software",
  "SaaS",
  "Artificial Intelligence",
  "Machine Learning",
  "Data Science",
  "Cybersecurity",
  "Cloud Computing",
  "Mobile Development",
  "Web Development",
  "DevOps",
  "IT Services",
  "Hardware",
  "Semiconductors",
  "Telecommunications",
  "Gaming",
  "EdTech",
  "PropTech",
  "LegalTech",
  "HealthTech",
  "AgriTech",
  "CleanTech",
  "RegTech",
  "InsurTech",
  "WealthTech",

  // Consulting
  "Consulting",
  "Management Consulting",
  "Strategy Consulting",
  "IT Consulting",
  "Financial Consulting",
  "HR Consulting",
  "Operations Consulting",
  "Digital Transformation",
  "Change Management",
  "Business Intelligence",

  // Marketing & Advertising
  "Marketing",
  "Digital Marketing",
  "Advertising",
  "Public Relations",
  "Social Media",
  "Content Marketing",
  "Brand Management",
  "Market Research",
  "SEO/SEM",
  "Growth Marketing",
  "Performance Marketing",
  "Influencer Marketing",
  "Email Marketing",
  "Marketing Analytics",

  // Sales
  "Sales",
  "Business Development",
  "Account Management",
  "Sales Operations",
  "Inside Sales",
  "Field Sales",
  "Channel Sales",
  "Customer Success",
  "Revenue Operations",

  // Healthcare
  "Healthcare",
  "Pharmaceuticals",
  "Biotechnology",
  "Medical Devices",
  "Digital Health",
  "Telemedicine",
  "Clinical Research",
  "Hospital Administration",
  "Healthcare IT",
  "Mental Health",
  "Dental",
  "Veterinary",

  // E-commerce & Retail
  "E-commerce",
  "Retail",
  "Fashion",
  "Luxury Goods",
  "Consumer Goods",
  "FMCG",
  "Marketplace",
  "Supply Chain",
  "Logistics",
  "Fulfillment",
  "Inventory Management",

  // Media & Entertainment
  "Media",
  "Entertainment",
  "Film & TV",
  "Music",
  "Publishing",
  "Journalism",
  "Broadcasting",
  "Streaming",
  "Content Creation",
  "Photography",
  "Design",
  "Animation",
  "Video Production",

  // Professional Services
  "Legal",
  "Law Firms",
  "Corporate Law",
  "Intellectual Property",
  "Accounting",
  "Audit",
  "Tax",
  "Human Resources",
  "Recruitment",
  "Staffing",
  "Training & Development",
  "Facilities Management",

  // Manufacturing & Industrial
  "Manufacturing",
  "Automotive",
  "Aerospace",
  "Defense",
  "Industrial Equipment",
  "Construction",
  "Architecture",
  "Engineering",
  "Chemical",
  "Materials",
  "Textiles",
  "Food & Beverage",
  "Consumer Electronics",

  // Energy & Environment
  "Energy",
  "Oil & Gas",
  "Renewable Energy",
  "Solar",
  "Wind",
  "Utilities",
  "Environmental Services",
  "Sustainability",
  "Carbon Management",
  "Water Management",

  // Transportation & Mobility
  "Transportation",
  "Airlines",
  "Shipping",
  "Freight",
  "Public Transit",
  "Ride-sharing",
  "Mobility",
  "Autonomous Vehicles",
  "Electric Vehicles",

  // Real Estate
  "Real Estate",
  "Property Management",
  "Commercial Real Estate",
  "Residential Real Estate",
  "Real Estate Investment",
  "Construction Management",
  "Urban Planning",

  // Education
  "Education",
  "Higher Education",
  "K-12 Education",
  "Online Learning",
  "Corporate Training",
  "Language Learning",
  "Skill Development",

  // Government & Non-Profit
  "Government",
  "Public Sector",
  "Non-Profit",
  "NGO",
  "International Development",
  "Social Impact",
  "Policy",
  "Think Tanks",

  // Hospitality & Travel
  "Hospitality",
  "Hotels",
  "Restaurants",
  "Travel",
  "Tourism",
  "Event Management",
  "Catering",
  "Food Service",

  // Sports & Fitness
  "Sports",
  "Fitness",
  "Wellness",
  "Recreation",
  "Sports Management",
  "Athletic Performance",

  // Agriculture & Food
  "Agriculture",
  "Food Production",
  "Food Technology",
  "Organic Farming",
  "Aquaculture",
  "Food Safety",

  // Other Emerging Sectors
  "Space Technology",
  "Quantum Computing",
  "Robotics",
  "3D Printing",
  "Virtual Reality",
  "Augmented Reality",
  "Blockchain",
  "Internet of Things",
  "Smart Cities",
  "Autonomous Systems",
];
