export const JOB_PLATFORMS = [
  { id: "linkedin", label: "LinkedIn", popular: true },
  { id: "indeed", label: "Indeed", popular: true },
  { id: "glassdoor", label: "Glassdoor", popular: true },
  { id: "welcome-jungle", label: "Welcome to the Jungle", popular: true },
  { id: "jobteaser", label: "JobTeaser", popular: true },
  { id: "apec", label: "APEC", popular: false },
  { id: "monster", label: "Monster", popular: false },
  { id: "stepstone", label: "StepStone", popular: false },
  { id: "xing", label: "XING", popular: false },
  { id: "angellist", label: "AngelList", popular: false },
  { id: "hired", label: "Hired", popular: false },
  { id: "stackoverflow", label: "Stack Overflow Jobs", popular: false },
  { id: "github", label: "GitHub Jobs", popular: false },
  { id: "dribbble", label: "Dribbble", popular: false },
  { id: "behance", label: "Behance", popular: false },
  { id: "upwork", label: "Upwork", popular: false },
  { id: "freelancer", label: "Freelancer", popular: false },
  { id: "fiverr", label: "Fiverr", popular: false },
  { id: "toptal", label: "Toptal", popular: false },
  { id: "dice", label: "Dice", popular: false },
  { id: "crunchboard", label: "CrunchBoard", popular: false },
];
