export const POPULAR_LOCATIONS = [
  // Major European Cities (Your Target Audience) - Most Popular First
  "Paris, France",
  "London, UK",
  "Berlin, Germany",
  "Amsterdam, Netherlands",
  "Barcelona, Spain",
  "Madrid, Spain",
  "Milan, Italy",
  "Rome, Italy",
  "Munich, Germany",
  "Zurich, Switzerland",
  "Vienna, Austria",
  "Dublin, Ireland",
  "Stockholm, Sweden",
  "Copenhagen, Denmark",
  "Brussels, Belgium",
  "Frankfurt, Germany",
  "Hamburg, Germany",
  "Lyon, France",
  "Lisbon, Portugal",
  "Prague, Czech Republic",
  "Warsaw, Poland",
  "Budapest, Hungary",
  "Helsinki, Finland",
  "Oslo, Norway",
  "Geneva, Switzerland",
  "Basel, Switzerland",
  "Toulouse, France",
  "Marseille, France",
  "Nice, France",
  "Bordeaux, France",
  "Lille, France",
  "Strasbourg, France",
  "Nantes, France",
  "Montpellier, France",
  "Manchester, UK",
  "Birmingham, UK",
  "Edinburgh, UK",
  "Glasgow, UK",
  "Leeds, UK",
  "Liverpool, UK",
  "Bristol, UK",
  "Cambridge, UK",
  "Oxford, UK",
  "Cologne, Germany",
  "Düsseldorf, Germany",
  "Stuttgart, Germany",
  "Leipzig, Germany",
  "Dresden, Germany",
  "Hannover, Germany",
  "Nuremberg, Germany",
  "Rotterdam, Netherlands",
  "The Hague, Netherlands",
  "Utrecht, Netherlands",
  "Eindhoven, Netherlands",
  "Valencia, Spain",
  "Seville, Spain",
  "Bilbao, Spain",
  "Malaga, Spain",
  "Zaragoza, Spain",
  "Palma, Spain",
  "Naples, Italy",
  "Turin, Italy",
  "Florence, Italy",
  "Bologna, Italy",
  "Genoa, Italy",
  "Venice, Italy",
  "Palermo, Italy",
  "Bari, Italy",
  "Antwerp, Belgium",
  "Ghent, Belgium",
  "Bruges, Belgium",
  "Luxembourg City, Luxembourg",
  "Gothenburg, Sweden",
  "Malmö, Sweden",
  "Aarhus, Denmark",
  "Bergen, Norway",
  "Trondheim, Norway",
  "Stavanger, Norway",
  "Tampere, Finland",
  "Turku, Finland",
  "Espoo, Finland",
  "Reykjavik, Iceland",
  "Tallinn, Estonia",
  "Riga, Latvia",
  "Vilnius, Lithuania",
  "Krakow, Poland",
  "Gdansk, Poland",
  "Wroclaw, Poland",
  "Poznan, Poland",
  "Bratislava, Slovakia",
  "Ljubljana, Slovenia",
  "Zagreb, Croatia",
  "Belgrade, Serbia",
  "Bucharest, Romania",
  "Sofia, Bulgaria",
  "Athens, Greece",
  "Thessaloniki, Greece",
  "Porto, Portugal",
  "Braga, Portugal",
  "Coimbra, Portugal",

  // Major US Cities (For International Students)
  "New York, USA",
  "San Francisco, USA",
  "Los Angeles, USA",
  "Boston, USA",
  "Seattle, USA",
  "Chicago, USA",
  "Austin, USA",
  "Washington DC, USA",
  "Miami, USA",
  "Atlanta, USA",
  "Denver, USA",
  "Portland, USA",
  "San Diego, USA",
  "Philadelphia, USA",
  "Phoenix, USA",
  "Dallas, USA",
  "Houston, USA",
  "Nashville, USA",
  "Charlotte, USA",
  "Raleigh, USA",
  "Minneapolis, USA",
  "Detroit, USA",
  "Pittsburgh, USA",
  "Cleveland, USA",
  "Salt Lake City, USA",
  "Las Vegas, USA",
  "Tampa, USA",
  "Orlando, USA",
  "Kansas City, USA",
  "Columbus, USA",
  "Indianapolis, USA",
  "Milwaukee, USA",
  "Cincinnati, USA",
  "Louisville, USA",
  "Memphis, USA",
  "New Orleans, USA",
  "San Antonio, USA",
  "Oklahoma City, USA",
  "Omaha, USA",
  "Des Moines, USA",
  "Madison, USA",
  "Ann Arbor, USA",
  "Boulder, USA",
  "Palo Alto, USA",
  "Santa Monica, USA",
  "Pasadena, USA",
  "Irvine, USA",
  "Scottsdale, USA",
  "Bellevue, USA",
  "Redmond, USA",
  "Arlington, USA",
  "Alexandria, USA",
  "Bethesda, USA",
  "Silver Spring, USA",
  "Cambridge, USA",
  "Somerville, USA",
  "Brooklyn, USA",
  "Queens, USA",
  "Manhattan, USA",
  "Jersey City, USA",
  "Hoboken, USA",

  // Canada
  "Toronto, Canada",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Calgary, Canada",
  "Ottawa, Canada",
  "Edmonton, Canada",
  "Winnipeg, Canada",
  "Quebec City, Canada",
  "Halifax, Canada",
  "Hamilton, Canada",
  "Kitchener, Canada",
  "London, Canada",
  "Victoria, Canada",
  "Saskatoon, Canada",
  "Regina, Canada",
  "St. John's, Canada",
  "Fredericton, Canada",
  "Charlottetown, Canada",
  "Whitehorse, Canada",
  "Yellowknife, Canada",

  // Asia-Pacific
  "Singapore",
  "Hong Kong",
  "Tokyo, Japan",
  "Seoul, South Korea",
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Adelaide, Australia",
  "Canberra, Australia",
  "Auckland, New Zealand",
  "Wellington, New Zealand",
  "Christchurch, New Zealand",
  "Bangkok, Thailand",
  "Kuala Lumpur, Malaysia",
  "Jakarta, Indonesia",
  "Manila, Philippines",
  "Ho Chi Minh City, Vietnam",
  "Hanoi, Vietnam",
  "Mumbai, India",
  "Delhi, India",
  "Bangalore, India",
  "Chennai, India",
  "Hyderabad, India",
  "Pune, India",
  "Kolkata, India",
  "Ahmedabad, India",
  "Taipei, Taiwan",
  "Shanghai, China",
  "Beijing, China",
  "Shenzhen, China",
  "Guangzhou, China",
  "Chengdu, China",
  "Hangzhou, China",
  "Nanjing, China",
  "Wuhan, China",
  "Xi'an, China",
  "Suzhou, China",

  // Middle East & Africa
  "Dubai, UAE",
  "Abu Dhabi, UAE",
  "Doha, Qatar",
  "Kuwait City, Kuwait",
  "Riyadh, Saudi Arabia",
  "Jeddah, Saudi Arabia",
  "Tel Aviv, Israel",
  "Jerusalem, Israel",
  "Haifa, Israel",
  "Beirut, Lebanon",
  "Amman, Jordan",
  "Cairo, Egypt",
  "Casablanca, Morocco",
  "Rabat, Morocco",
  "Tunis, Tunisia",
  "Algiers, Algeria",
  "Lagos, Nigeria",
  "Abuja, Nigeria",
  "Cape Town, South Africa",
  "Johannesburg, South Africa",
  "Durban, South Africa",
  "Pretoria, South Africa",
  "Nairobi, Kenya",
  "Kampala, Uganda",
  "Dar es Salaam, Tanzania",
  "Addis Ababa, Ethiopia",
  "Accra, Ghana",
  "Dakar, Senegal",
  "Kigali, Rwanda",
  "Lusaka, Zambia",
  "Harare, Zimbabwe",
  "Gaborone, Botswana",
  "Windhoek, Namibia",
  "Maputo, Mozambique",
  "Antananarivo, Madagascar",
  "Port Louis, Mauritius",

  // Latin America
  "Mexico City, Mexico",
  "Guadalajara, Mexico",
  "Monterrey, Mexico",
  "Tijuana, Mexico",
  "Puebla, Mexico",
  "Cancun, Mexico",
  "Merida, Mexico",
  "Leon, Mexico",
  "Juarez, Mexico",
  "Toluca, Mexico",
  "São Paulo, Brazil",
  "Rio de Janeiro, Brazil",
  "Brasília, Brazil",
  "Salvador, Brazil",
  "Fortaleza, Brazil",
  "Belo Horizonte, Brazil",
  "Manaus, Brazil",
  "Curitiba, Brazil",
  "Recife, Brazil",
  "Porto Alegre, Brazil",
  "Buenos Aires, Argentina",
  "Córdoba, Argentina",
  "Rosario, Argentina",
  "Mendoza, Argentina",
  "La Plata, Argentina",
  "Mar del Plata, Argentina",
  "Salta, Argentina",
  "Santa Fe, Argentina",
  "Santiago, Chile",
  "Valparaíso, Chile",
  "Concepción, Chile",
  "La Serena, Chile",
  "Antofagasta, Chile",
  "Temuco, Chile",
  "Rancagua, Chile",
  "Talca, Chile",
  "Arica, Chile",
  "Iquique, Chile",
  "Lima, Peru",
  "Arequipa, Peru",
  "Trujillo, Peru",
  "Chiclayo, Peru",
  "Piura, Peru",
  "Iquitos, Peru",
  "Cusco, Peru",
  "Huancayo, Peru",
  "Chimbote, Peru",
  "Tacna, Peru",
  "Bogotá, Colombia",
  "Medellín, Colombia",
  "Cali, Colombia",
  "Barranquilla, Colombia",
  "Cartagena, Colombia",
  "Cúcuta, Colombia",
  "Soledad, Colombia",
  "Ibagué, Colombia",
  "Bucaramanga, Colombia",
  "Soacha, Colombia",
  "Caracas, Venezuela",
  "Maracaibo, Venezuela",
  "Valencia, Venezuela",
  "Barquisimeto, Venezuela",
  "Maracay, Venezuela",
  "Ciudad Guayana, Venezuela",
  "San Cristóbal, Venezuela",
  "Maturín, Venezuela",
  "Ciudad Bolívar, Venezuela",
  "Cumana, Venezuela",
  "Quito, Ecuador",
  "Guayaquil, Ecuador",
  "Cuenca, Ecuador",
  "Santo Domingo, Ecuador",
  "Ambato, Ecuador",
  "Manta, Ecuador",
  "Portoviejo, Ecuador",
  "Machala, Ecuador",
  "Loja, Ecuador",
  "Riobamba, Ecuador",
  "La Paz, Bolivia",
  "Santa Cruz, Bolivia",
  "Cochabamba, Bolivia",
  "Sucre, Bolivia",
  "Oruro, Bolivia",
  "Tarija, Bolivia",
  "Potosí, Bolivia",
  "Trinidad, Bolivia",
  "Cobija, Bolivia",
  "Riberalta, Bolivia",
  "Asunción, Paraguay",
  "Ciudad del Este, Paraguay",
  "San Lorenzo, Paraguay",
  "Luque, Paraguay",
  "Capiatá, Paraguay",
  "Lambaré, Paraguay",
  "Fernando de la Mora, Paraguay",
  "Limpio, Paraguay",
  "Ñemby, Paraguay",
  "Encarnación, Paraguay",
  "Montevideo, Uruguay",
  "Salto, Uruguay",
  "Paysandú, Uruguay",
  "Las Piedras, Uruguay",
  "Rivera, Uruguay",
  "Maldonado, Uruguay",
  "Tacuarembó, Uruguay",
  "Melo, Uruguay",
  "Mercedes, Uruguay",
  "Artigas, Uruguay",

  // Remote Options
  "Remote",
  "Remote - Europe",
  "Remote - Worldwide",
  "Remote - EU timezone",
  "Remote - Americas",
  "Remote - Asia-Pacific",
  "Hybrid",
  "Hybrid - Europe",
  "Hybrid - US",

  // Regions
  "Europe",
  "North America",
  "EMEA",
  "Asia-Pacific",
  "Latin America",
  "Middle East",
  "Africa",
  "Scandinavia",
  "Benelux",
  "DACH",
  "Iberia",
  "Eastern Europe",
  "Western Europe",
  "Central Europe",
  "Southern Europe",
  "Northern Europe",

  // Countries (for broader searches)
  "France",
  "United Kingdom",
  "Germany",
  "Spain",
  "Italy",
  "Netherlands",
  "Switzerland",
  "Austria",
  "Belgium",
  "Sweden",
  "Denmark",
  "Norway",
  "Finland",
  "Ireland",
  "Portugal",
  "Poland",
  "Czech Republic",
  "Hungary",
  "Slovakia",
  "Slovenia",
  "Croatia",
  "Serbia",
  "Romania",
  "Bulgaria",
  "Greece",
  "Estonia",
  "Latvia",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Cyprus",
  "Iceland",
  "United States",
  "Canada",
  "Australia",
  "New Zealand",
  "Japan",
  "South Korea",
  "Singapore",
  "Hong Kong",
  "Taiwan",
  "India",
  "China",
  "Thailand",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Vietnam",
  "Brazil",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "Mexico",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Egypt",
  "Morocco",
  "Israel",
  "UAE",
  "Saudi Arabia",
  "Qatar",
  "Turkey",
  "Russia",
  "Ukraine",
];
